version: 2
jobs:
  test:
    docker:
    - image: circleci/node:carbon
    working_directory: ~/js-module
    steps:
    - checkout
    - run:
        name: Set NPM auth token
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
    - restore_cache:
        keys:
        - v1-npm-cache-{{ checksum "yarn.lock" }}
        - v1-npm-cache # used if checksum fails
    - run: yarn install
    - save_cache:
        key: v1-npm-cache-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules/
    - run:
        name: Building packages
        command: yarn test
  build:
    docker:
      - image: circleci/node:carbon

    working_directory: ~/f8-ad-tool
    steps:
      - checkout
      - run:
          name: Set NPM auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "yarn.lock" }}
            - v1-npm-cache # used if checksum fails
      - run: yarn install
      - save_cache:
          key: v1-npm-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - run:
          name: Building packages
          command: yarn build

workflows:
  version: 2
  test-build:
    jobs:
      - build:
          context: NPM
      - test:
          context: NPM
